// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvqDjFAG9oM2Su4MqnqzR3kVOzcfkalA',
    appId: '1:328135743793:web:e4fc1919cb089d5fdef810',
    messagingSenderId: '328135743793',
    projectId: 'education-corner-745ec',
    authDomain: 'education-corner-745ec.firebaseapp.com',
    storageBucket: 'education-corner-745ec.appspot.com',
    measurementId: 'G-PKYBHVBRZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_9nF1VrGgSpIZfC0_Da6m17PRtyYTeU',
    appId: '1:328135743793:android:c973aa4af0277577def810',
    messagingSenderId: '328135743793',
    projectId: 'education-corner-745ec',
    storageBucket: 'education-corner-745ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFLllLjRukpLfohh9GIuxQmE2TqbtBEI',
    appId: '1:328135743793:ios:e05c01268b3d64a4def810',
    messagingSenderId: '328135743793',
    projectId: 'education-corner-745ec',
    storageBucket: 'education-corner-745ec.appspot.com',
    iosClientId: '328135743793-o8jtf2vd240vr4n51et0s217cfjdqfmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNFLllLjRukpLfohh9GIuxQmE2TqbtBEI',
    appId: '1:328135743793:ios:e05c01268b3d64a4def810',
    messagingSenderId: '328135743793',
    projectId: 'education-corner-745ec',
    storageBucket: 'education-corner-745ec.appspot.com',
    iosClientId: '328135743793-o8jtf2vd240vr4n51et0s217cfjdqfmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduCorner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvqDjFAG9oM2Su4MqnqzR3kVOzcfkalA',
    appId: '1:328135743793:web:0139a15a81f47c22def810',
    messagingSenderId: '328135743793',
    projectId: 'education-corner-745ec',
    authDomain: 'education-corner-745ec.firebaseapp.com',
    storageBucket: 'education-corner-745ec.appspot.com',
    measurementId: 'G-C5V4V7MCN3',
  );
}
